import {inject, Injectable} from "@angular/core";
import {WebStorageService} from "./web-storage.service";
import {IWord} from "../interfaces";

@Injectable({
  providedIn: 'root',
})
export class WordService {
  private webStorage = inject(WebStorageService);
  wordsList = [
    'Event loop',
    'Callback function',
    'Argument',
    'Design pattern',
    'Waterfall',
    'Scrum Master',
    'Encapsulation',
    'Singleton',
    'Variable',
    'Decorator',
    'Feature flag',
    'API',
    'Promise',
    'Critical Rendering Path',
    'Interface',
    'Inheritance',
    'Polymorphism',
    'Abstract Class',
    'Class',
    'Interpolation',
    'click',
    'Observer',
    'Developer Tools',
    'Overloading',
    'Restart',
    'REST',
    'HTTP Protocol',
    'Refresh token',
    'Tab',
    'Sprint',
    'Story Point',
    'Refinement',
    'Daily Stand-up Meeting',
    'Day off',
    'Sick leave',
    'Training center',
    'Delivery Manager',
    'Senior',
    'Resource Manager',
    'Team Lead',
    'HR',
    'Routing',
    'Rendering',
    'Angular',
    'React.js',
    'Dependency Injection',
    'NPM',
    'Global Protect',
    'Google Authenticator',
    'node_modules',
    'Browser',
    'Browser Tab',
    'Incognito Window',
    'Bookmark',
    'Extension',
    'Settings',
    'Performance',
    'Memory',
    'Explorer',
    'Network',
    'LD',
    'EPAM',
    'Benefit',
    'Probation',
    'Salary',
    'Assessment',
    'Colleague',
    'Retrospective',
    'Bench',
    'Multitasking',
    'Debugger',
    'Compiler',
    'Submit',
    'Parameter',
    'Overtime',
    'Vacation',
    'Certification',
    'Type',
    'Redux',
    'Bug',
    'Function Expression',
    'Function Declaration',
    'Framework',
    'Upgrade',
    'Back-End',
    'Front-End',
    'Soft skill',
    'AI',
    'Mentor',
    'Mentee',
    'Intern',
    'Junior',
    'Mid Developer',
    'Senior Developer',
    'Team-Lead',
    'Engineering Manager',
    'Junior Architect',
    'Senior Architect',
    'Tech-Lead',
    'Project Manager',
    'Scrum Master',
    'Delivery Manager',
    'Business Analyst',
    'Product Owner',
    'Project Manager',
    'QA',
    'Notification',
    'Router',
    'Controller',
    'Service',
    'Repository',
    'Database',
    'Middleware',
    'Query Parameter',
    'Request',
    'Response',
    'Microservice Architecture',
    'Monolithic Architecture',
    'API Gateway',
    'Cron-job Scheduler',
    'Mongo DB',
    'Mongoose',
    'MySQL',
    'SQL',
    'Git',
    'GitHub',
    'Express.js',
    'Nest.js',
    'Vue.js',
    'Next.js',
    'Bootstrap',
    'JQuery',
    'Pull Request',
    'Master Branch',
    'Commit',
    'Branching Strategy',
    'Rebase',
    'Code review',
    'Croissant',
    'Downstream merge',
    '“use strict”',
    'Console',
    'Variables',
    'Declaration',
    'while loop',
    'for loop',
    'switch',
    'Comment',
    'String',
    'Number',
    'BigInt',
    'Symbol',
    'Boolean',
    'Null',
    'Undefined',
    'Object',
    'Array',
    'Map',
    'WeakMap',
    'Set',
    'WeakSet',
    'Iteration',
    'Destructuring',
    'JSON',
    'Array methods',
    'Recursion',
    'Rest parameters',
    'Closure',
    'Garbage collector',
    'Constructor',
    'setTimeout',
    'setInterval',
    'Decorator',
    'Getter',
    'Setter',
    'Private Variable',
    'Public Variable',
    'Protected Variable',
    'Prototype',
    'Static Method',
    'Static Property',
    'try catch',
    'async/await',
    'Promise',
    'Microtask',
    'Macrotask',
    'Module',
    'Mixin',
    'Enum',
    'DOM Tree',
    'Breadcrumbs',
    'Header',
    'Footer',
    'Navigation',
    'Registration',
    'Login',
    'Local storage',
    'Session storage',
    'SVG',
    'JPEG',
    'PNG',
    'JetBrains',
    'WebStorm',
    'Telescope',
    'Service provider',
    'Font size',
    'Font weight',
    'Hover',
    'Event lIstener',
    'Grid system',
    'Uppercase',
    'Lowercase',
    'Pixel perfect',
    'Best practice',
    'Margin',
    'Padding',
    'Border radius',
    'Singleton',
    'Factory',
    'Abstract Factory',
    'Prototype',
    'Adapter',
    'Decorator',
    'Webpack',
    'TypeScript',
    'Linter',
    'Component',
    'Class Component',
    'Jest',
    'Single Responsibility Principle',
    'Open-Closed Principle',
    'Liskov Substitution Principle',
    'Interface Segregation Principle',
    'Dependency Inversion Principle',
    'Capacity',
    'Higher Order Function',
    'Pure Function',
    'Impure Function',
    'Keyboard',
    'Desktop Application',
    'Mobile Application',
    'Web Application',
    'Screenshot',
    'Curly braces',
    'Unit head',
    'Postfix increment',
    'Prefix increment',
    'Postfix decrement',
    'Prefix decrement',
    'Pre-loading',
    'Lazy-loading',
    'Stack overflow',
    'Stackblitz',
    'W3Schools',
    'open-source',
    'Mozilla Developer Network',
    'Documentation',
    'Testing pyramid',
    'Optimization',
    'File System',
    'Folder',
    'File',
    'Regression',
    'git stash',
    'Pair-programming',
    'Solution Architect',
    'Refresh',
    'Text editor',
    'Computer',
    'Laptop',
    'Readme',
    'Credentials',
    'span',
    'div',
    'iframe',
    'Design Pattern',
    'Single Page Application',
    'Root cause',
    'JS Unit',
    'Maintainable',
    'Extendable',
    'Performance issue',
    'Program',
    'Instance',
    'K.I.S.S',
    'Y.A.G.N.I',
    'D.R.Y',
    'LESS',
    'Micro frontend',
    'Implementation',
    'Sprint Planning',
    'Daily Standup Meeting',
    'Retrospective',
    'Estimation',
    'Poker Planning',
    'Story point',
    'Metadata',
    'Epic',
    'Agile',
    'Feature',
    'GlobalProtect',
    'OPSWAT',
    'Time management',
    'Microsoft Authenticator',
    'Backward compatibility',
    'npm install',
    'Command Line',
    'git pull',
    'Template',
    'Copy-paste',
    'ChatGPT',
    'Cache storage',
    'Copilot',
    'Assessment',
    'index.ts',
    'Meeting room',
    'require',
    'Workspace',
    'Hello world',
    'Team building',
    'Self-presentation',
    'Committee head',
    'Interviewer',
    'Interview',
    'Checkbox',
    'SASS',
    'Error handling',
    'Radio button',
    'Textarea',
    'Input field',
    'index.html',
    'Slider',
    'Dialog',
    'Tooltip',
    'git push',
    'Date picker',
    'Spinner',
    'Modal window',
    'Pagination',
    'Switch toggle',
    'Table',
    'CRUD',
    'index.js',
    'Visual Studio Code',
    'git rebase',
    'Label',
    'Localhost',
    'Domain',
    'Upload',
    'Host',
    'export',
    'void',
    'Syntax',
    'Download',
    'Configuration',
    'Babel.js',
    'Convert',
    'Object Literal',
    'Installation',
    'import',
    'SCSS',
    'Web Worker',
    'Attribute',
    'Cookies',
    'Socket',
    'Serverless',
    'Merge conflict',
    'Deploy',
    'Event Emitter',
    'Version Control System',
    'Demo',
    'Betta version',
    'Algorithm',
    'WiFi',
    'Internet',
    'Protocol',
    'Submit',
    'Validation',
    'Loading',
    'Reloading',
    'Reset',
    'Sprint Planning',
    'Backlog',
    'Software',
    'Hardware',
    'Key developer',
    'DevOps',
    'Kanban',
    'Agile Manifesto',
    'Azure',
    'Waterfall',
    'udemy',
    'Google',
    'Atlassian',
    'GitLab',
    'return',
    'var',
    'let',
    'const',
    'StackBlitz',
    'instanceof',
    'Exception',
    'Callback Function',
    'Drag’n’Drop',
    'Scroll',
    'Regular Expression',
    'Bootstrap',
    'Vue.js',
    'Fullstack Developer',
    'AJAX',
    'Form',
    'Infinite loop',
    'Teams',
    'Outlook',
    '.gitignore',
    'Server',
    'Selector',
    'Tutorial',
    'Snapshot',
    'EventBridge',
    '200 OK',
    'Cross Site Scripting',
    'Technical Debt',
    'GET',
    'DELETE',
    'PUT',
    'POST',
    'PATCH',
    'Request Body',
    'Request Header',
    'content-type',
    'Proxy server',
    'Event Bus',
    'AWS Lambda',
    'Postgres',
    'Permission',
    'Self-organized',
    'Filtering',
    'Mapping',
    'Sorting',
    'Reducer',
    'Dispatch',
    'QR Code',
    'Secret Key',
    'Bitbucket',
    'Dropdown',
    'Operator',
    'Operand',
    'Lexical Environment',
    'Performance',
    'Event Listener',
    'Stringify',
    'Canvas',
    'Chart',
    'href',
    'Link',
    'Sick leave',
    'Hardcode',
    'Z-index',
    'Pseudo-element',
    'User Interface',
    'Media query',
    'Flexbox',
    'V8 Engine',
    'Query',
    'Data',
    'Outsource Company',
    'Primitive Type',
    'Reference Type',
    'Execution Context',
    'Heap',
    'Stack',
    'Hashing',
    'Decoding',
    'Encrypt',
    'Decrypt',
    'Migration',
    'Circular Dependency',
    'libuv',
    'USB',
    'Open space',
    'Remote work',
    'EPAM Anywhere',
    'Solution Architect',
    'package.json',
    'Compensation Manager',
    'LinkedIn',
    'Rework',
    'Shadow DOM',
    'Virtual DOM',
  ];

  generateWords(): void {
    const shuffledWords = this.shuffle(this.wordsList);
    const modifiedList = shuffledWords.map((word) => ({ id: crypto.randomUUID(), value: word }));
    this.webStorage.remove('words', 'LOCAL');
    this.webStorage.set('words', modifiedList, 'LOCAL');
  }

  shuffle(words: string[]): string[] {
    const shuffledArray = words;
    for (let i = shuffledArray.length - 1; i > 0; --i) {
      const j = Math.floor(Math.random() * (i + 1));
      const temp = shuffledArray[i];
      shuffledArray[i] = shuffledArray[j];
      shuffledArray[j] = temp;
    }
    return shuffledArray;
  }

  getWords(count: number): IWord[] {
    const words = this.webStorage.get('words', 'LOCAL') as IWord[];
    const wordsChunk = words.splice(0, count);
    this.webStorage.set('words', words, 'LOCAL');
    return wordsChunk;
  }
}
